---
title: "Pdgfrb-INTACT JGA Dissection Code"
author: "Jonathan Nelson"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("BiocManager")) {install.packages("BiocManager"); require("BiocManager")}
if (!require("tibble")) {install.packages("tibble"); require("tibble")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")} #color
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("kableExtra")) {install.packages("kableExtra"); require("kableExtra")} # for color brewer
if (!require("gplots")) {install.packages("gplots"); require("gplots")} # for color brewer
if (!require("clusterProfiler")) {BiocManager::install('clusterProfiler'); require("clusterProfiler")}
if (!require("enrichplot")) {BiocManager::install('enrichplot'); require("enrichplot")}
library("EnhancedVolcano")
library(UpSetR)
library(ComplexHeatmap)
# install.packages("ggtext")
library(ggtext)
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)

```

# Load Dataset

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

rm(list = ls())

SO <- readRDS(here("Datasets", "GFPcombined.072824.rds"))

load(here("Datasets", "GFP_Special.RData"))

# colnames(SO)

colnames(SO) <- make.unique(str_remove(colnames(SO), "-.*"))
rownames(df) <- make.unique(str_remove(rownames(df), "-.*"))

# rownames(df)

df2 <- as.data.frame(df)

SO2 <- AddMetaData(SO, df)

DimPlot(SO2, group.by = "Special")
DimPlot(SO2, group.by = "class.Merge")

```

# Filter and Save Object

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}


SO3 <- subset(SO2, subset = class.Merge == "Fibroblasts", invert = T)
SO3 <- subset(SO3, subset = class.Merge == "Medullary Fibroblasts", invert = T)
SO3 <- subset(SO3, subset = class.Merge == "Proliferating", invert = T)

DimPlot(SO3)

SO4 <- SCTransform(SO3) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:15) %>%
    FindClusters(resolution = 2) %>%
    RunUMAP(dims = 1:15)


SO5 <- subset(SO4, subset = nFeature_RNA < 2000)

VlnPlot(SO5, "nFeature_RNA")

SO6 <- SCTransform(SO5) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:15) %>%
    FindClusters(resolution = 2) %>%
    RunUMAP(dims = 1:15)

DimPlot(SO6)

VlnPlot(SO6, "nFeature_RNA")

SO7 <- subset(SO6, subset = seurat_clusters == 9, invert = T)

SO7 <- subset(SO7, subset = Special == "Fibroblast A", invert = T)
SO7 <- subset(SO7, subset = Special == "Fibroblast B", invert = T)
SO7 <- subset(SO7, subset = Special == "Fibroblast C", invert = T)

SO8 <- SCTransform(SO7) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:10) %>%
    FindClusters(resolution = 1) %>%
    RunUMAP(dims = 1:10)

DimPlot(SO8, label = T)

VlnPlot(SO8, "nFeature_RNA")

DimPlot(SO8, group.by = "Special")

DimPlot(SO8, group.by = "class.Merge")

VlnPlot(SO8, "Pdgfra", group.by = "Special")

SO8

FeaturePlot(SO8, "Adra1a", order = TRUE)

SO8@meta.data <- SO8@meta.data %>% mutate(class.JGA = dplyr::case_when(
seurat_clusters == 0 ~ "Pericyte",
seurat_clusters == 1 ~ "Afferent VSMC",
seurat_clusters == 2 ~ "Pericyte",
seurat_clusters == 3 ~ "Efferent VSMC",
seurat_clusters == 4 ~ "Pericyte",
seurat_clusters == 5 ~ "Pericyte",
seurat_clusters == 6 ~ "Granular Cell",
seurat_clusters == 7 ~ "Pericyte",
seurat_clusters == 8 ~ "Pericyte",
seurat_clusters == 9 ~ "EG Mesangial Cell",
seurat_clusters == 10 ~ "IG Mesangial Cell",
))

DimPlot(SO8, group.by = "class.JGA")

FeaturePlot(SO8, "Abcc9", order = TRUE)
FeaturePlot(SO8, "Adora1", order = TRUE)
FeaturePlot(SO8, "Gata3", order = TRUE)
FeaturePlot(SO8, "Rgs5", order = TRUE)
FeaturePlot(SO8, "Hpse2", order = TRUE)
FeaturePlot(SO8, "Agtr1a", order = TRUE)

DimPlot(SO8, split.by = "Sample", group.by = "class.JGA")

SO8@meta.data$class.JGA <- factor(SO8@meta.data$class.JGA, levels = c("Pericyte", "Efferent VSMC","Afferent VSMC", "Granular Cell",  "EG Mesangial Cell", "IG Mesangial Cell"))

DimPlot(SO8, group.by = "class.JGA")

DimPlot(SO8, group.by = "class.JGA", label = T)

saveRDS(SO8, here("Datasets", "INTACT_JGA.rds"))

```

# Session Info

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

sessionInfo()

```


  