---
title: "Pdgfrb-INTACT JGA Dissection Code"
author: "Jonathan Nelson"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("BiocManager")) {install.packages("BiocManager"); require("BiocManager")}
if (!require("tibble")) {install.packages("tibble"); require("tibble")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")} #color
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("kableExtra")) {install.packages("kableExtra"); require("kableExtra")} # for color brewer
if (!require("gplots")) {install.packages("gplots"); require("gplots")} # for color brewer
if (!require("clusterProfiler")) {BiocManager::install('clusterProfiler'); require("clusterProfiler")}
if (!require("enrichplot")) {BiocManager::install('enrichplot'); require("enrichplot")}
library("EnhancedVolcano")
library(UpSetR)
library(ComplexHeatmap)
install.packages("ggtext")
library(ggtext)
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)

```


# Load Dataset

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

rm(list = ls())

SO <- readRDS(here("Datasets", "GFPcombined.072824.rds"))

load(here("Datasets", "GFP_Special.RData"))

colnames(SO)

colnames(SO) <- make.unique(str_remove(colnames(SO), "-.*"))
rownames(df) <- make.unique(str_remove(rownames(df), "-.*"))

rownames(df)

df2 <- as.data.frame(df)

SO2 <- AddMetaData(SO, df)

DimPlot(SO2, group.by = "Special")
DimPlot(SO2, group.by = "class.Merge")

```


```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}


SO3 <- subset(SO2, subset = class.Merge == "Fibroblasts", invert = T)
SO3 <- subset(SO3, subset = class.Merge == "Medullary Fibroblasts", invert = T)
SO3 <- subset(SO3, subset = class.Merge == "Proliferating", invert = T)

DimPlot(SO3)

SO4 <- SCTransform(SO3) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:15) %>%
    FindClusters(resolution = 2) %>%
    RunUMAP(dims = 1:15)

DimPlot(SO4)

VlnPlot(SO4, "nFeature_RNA")

SO5 <- subset(SO4, subset = nFeature_RNA < 2000)

VlnPlot(SO5, "nFeature_RNA")

SO6 <- SCTransform(SO5) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:15) %>%
    FindClusters(resolution = 2) %>%
    RunUMAP(dims = 1:15)

DimPlot(SO6)

VlnPlot(SO6, "nFeature_RNA")

SO7 <- subset(SO6, subset = seurat_clusters == 9, invert = T)

SO7 <- subset(SO7, subset = Special == "Fibroblast A", invert = T)
SO7 <- subset(SO7, subset = Special == "Fibroblast B", invert = T)
SO7 <- subset(SO7, subset = Special == "Fibroblast C", invert = T)

SO8 <- SCTransform(SO7) %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:10) %>%
    FindClusters(resolution = 1) %>%
    RunUMAP(dims = 1:10)

DimPlot(SO8, label = T)

VlnPlot(SO8, "nFeature_RNA")

DimPlot(SO8, group.by = "Special")

DimPlot(SO8, group.by = "class.Merge")

VlnPlot(SO8, "Pdgfra", group.by = "Special")

SO8

FeaturePlot(SO8, "Adra1a", order = TRUE)

SO8@meta.data <- SO8@meta.data %>% mutate(class.JGA = dplyr::case_when(
seurat_clusters == 0 ~ "Pericyte",
seurat_clusters == 1 ~ "Afferent VSMC",
seurat_clusters == 2 ~ "Pericyte",
seurat_clusters == 3 ~ "Efferent VSMC",
seurat_clusters == 4 ~ "Pericyte",
seurat_clusters == 5 ~ "Pericyte",
seurat_clusters == 6 ~ "Granular Cell",
seurat_clusters == 7 ~ "Pericyte",
seurat_clusters == 8 ~ "Pericyte",
seurat_clusters == 9 ~ "EG Mesangial Cell",
seurat_clusters == 10 ~ "IG Mesangial Cell",
))

DimPlot(SO8, group.by = "class.JGA")

FeaturePlot(SO8, "Abcc9", order = TRUE)
FeaturePlot(SO8, "Adora1", order = TRUE)
FeaturePlot(SO8, "Gata3", order = TRUE)
FeaturePlot(SO8, "Rgs5", order = TRUE)
FeaturePlot(SO8, "Hpse2", order = TRUE)
FeaturePlot(SO8, "Agtr1a", order = TRUE)

DimPlot(SO8, split.by = "Sample", group.by = "class.JGA")

SO8@meta.data$class.JGA <- factor(SO8@meta.data$class.JGA, levels = c("Pericyte", "Afferent VSMC", "Efferent VSMC", "Granular Cell",  "EG Mesangial Cell", "IG Mesangial Cell"))

```

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DefaultAssay(SO8) <- "RNA"
Idents(SO8) <- SO8@meta.data$class.JGA

markers.to.plot1 <- c("Pdgfrb",
                      "Abcc9",
                      "Acta2",
                      "Adra1a",
                      "Tenm2",
                      "Ren1",
                      "Gata3",
                      "Pdgfra",
                      "Piezo2",
                      "Agtr1a",
                      "Adora1"
                            )

markers.to.plot2 <- c("Pdgfrb",
                      "Abcc9",
                      "Acta2",
                      "Adra1a",
                      "Tenm2",
                      "Ren1",
                      "Piezo2"
                      )

markers.to.plot3 <- c("Pdgfrb",
                      "Acta2",
                      "Ren1",
                      "Piezo2"
                      )


DotPlot(SO8,
        features = markers.to.plot3,
        dot.scale = 8,
        dot.min = 0,
        scale.max = 100,
        scale.min = 0,
        col.min = -2.5,
        col.max = 2.5,
        scale = FALSE,
        group.by = "class.JGA") +
  coord_flip() +
  theme_classic() +
  ggtitle("Populations Markers") +
  theme(axis.line = element_line(size = 1, colour = "black"),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        text = element_text(size = 20),
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5)) +
  xlab(NULL) +
  ylab(NULL)



markers.to.plot4 <- c("Gja1",
                      "Gja3",
                      "Gja4",
                      "Gjb2",
                      "Gjb4",
                      "Gjb3",
                      "Gjb5",
                      "GJb1",
                      "Gja9",
                      "GJa5",
                      "Gja10",
                      "Panx"
                      )

DotPlot(SO8,
        features = markers.to.plot4,
        dot.scale = 8,
        dot.min = 0,
        scale.max = 10,
        scale.min = 0,
        col.min = -2.5,
        col.max = 2.5,
        scale = FALSE,
        group.by = "class.JGA") +
  coord_flip() +
  theme_classic() +
  ggtitle("Populations Markers") +
  theme(axis.line = element_line(size = 1, colour = "black"),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        text = element_text(size = 20),
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5)) +
  xlab(NULL) +
  ylab(NULL)


Idents(SO8) <- SO8@meta.data$class.JGA

df_ex_mes <- FindMarkers(SO8, ident.1 = "EG Mesangial Cell", min.pct = 0.1, logfc.threshold = 0.25)


df_Ex_mes_pos <- subset(df_ex_mes, p_val_adj < 0.05 & avg_log2FC > 0)

rownames(df_Ex_mes_pos)


VlnPlot(SO8, "Tjp1")

VlnPlot(SO8, "Gja5")


VlnPlot(SO8, "Ren1")


VlnPlot(SO8, "Ptger2")
VlnPlot(SO8, "Ptger4")
VlnPlot(SO8, "Ptger3")
VlnPlot(SO8, "Ptger1")

VlnPlot(SO8, "Agtr1a")
VlnPlot(SO8, "Agtr1b")
VlnPlot(SO8, "Agt")
VlnPlot(SO8, "Agtr2")
VlnPlot(SO8, "Mmp7")
VlnPlot(SO8, "Gja5")
VlnPlot(SO8, "Nt5e")
VlnPlot(SO8, "Pdgfrb")

VlnPlot(SO8, "Adora1")
VlnPlot(SO8, "Rgs5")
VlnPlot(SO8, "Dgkg")


```

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.width=10}


df7 <- FindAllMarkers(SO8, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
df7 %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)

top5 <- df7 %>% distinct(gene, .keep_all = TRUE) %>% group_by(cluster) %>% top_n(5, avg_log2FC)

DotPlot(SO8,
        features = top5$gene,
        cols = c("#0099ff", "#dc143c"),
        dot.scale = 8,
           dot.min = 0,
           scale.max = 100,
           scale.min = 0,
           col.min = -2.5,
           col.max = 2.5) + 
 # scale_y_discrete(limits = c(Prol"MD", "TAL β", "TAL α")) + 
  theme(axis.text.x = element_text(),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 9)) + 
  RotatedAxis() + 
  ggtitle("Top 5 Pdgfrb JGA DEG") 

```

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.width=15}


top10 <- df7 %>% distinct(gene, .keep_all = TRUE) %>% group_by(cluster) %>% top_n(10, avg_log2FC)

DotPlot(SO8,
        features = top10$gene,
        cols = c("#0099ff", "#dc143c"),
        dot.scale = 8,
           dot.min = 0,
           scale.max = 100,
           scale.min = 0,
           col.min = -2.5,
           col.max = 2.5) + 
 # scale_y_discrete(limits = c(Prol"MD", "TAL β", "TAL α")) + 
  theme(axis.text.x = element_text(),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 9)) + 
  RotatedAxis() + 
  ggtitle("Top 10 Pdgfrb JGA DEG") 

```

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

#filter to only include rows with p_val_adj < 0.05

df8 <- df7 %>% filter(p_val_adj < 0.05)

clustered_genes <- split(df8$gene, df8$cluster)

list_to_matrix(clustered_genes)

m1 = make_comb_mat(clustered_genes)
m1

set_name(m1)
comb_name(m1)
comb_size(m1)
set_size(m1)
m1 <- m1[comb_size(m1) >= 2]
UpSet(m1, set_order = rev(c("Pericyte", "Afferent VSMC", "Efferent VSMC", "Granular Cell",  "EG Mesangial Cell", "IG Mesangial Cell")), comb_order = order(comb_size(m1)))




```


# Volcano Plots

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DimPlot(SO8, group.by = "class.JGA")

DimPlot(SO8, group.by = "class.JGA", 
        cols = c("EG Mesangial Cell" = "yellow", 
                 "IG Mesangial Cell" = "blue")) +
  ggtitle("")


```

## IG vs. EG Mes

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DimPlot(SO8)

df6 <- FindMarkers(SO8, ident.1 = c("IG Mesangial Cell"), ident.2 = c("EG Mesangial Cell"), min.pct = 0.1, logfc.threshold = 0.25)

df6 <- df6 %>% filter(p_val_adj < 0.05)

EnhancedVolcano(df6,
                lab = rownames(df6),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-4, 4),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

```

## Afferent VSMC vs. EG Mes

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DimPlot(SO8, group.by = "class.JGA")

DimPlot(SO8, group.by = "class.JGA", 
        cols = c("EG Mesangial Cell" = "yellow", 
                 "Afferent VSMC" = "blue")) +
  ggtitle("")


```


```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

df12 <- FindMarkers(SO8, ident.1 = c("Afferent VSMC"), ident.2 = c("EG Mesangial Cell"), min.pct = 0.1, logfc.threshold = 0.25)

df12 <- df12 %>% filter(p_val_adj < 0.05)

EnhancedVolcano(df12,
                lab = rownames(df12),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-4, 4),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

```


## Afferent VSMC vs. Efferent VSMC

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DimPlot(SO8, group.by = "class.JGA")

DimPlot(SO8, group.by = "class.JGA", 
        cols = c("Efferent VSMC" = "yellow", 
                 "Afferent VSMC" = "blue")) +
  ggtitle("")


```


```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

df12 <- FindMarkers(SO8, ident.1 = c("Afferent VSMC"), ident.2 = c("Efferent VSMC"), min.pct = 0.1, logfc.threshold = 0.25)

df12 <- df12 %>% filter(p_val_adj < 0.05)

EnhancedVolcano(df12,
                lab = rownames(df12),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-4, 4),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

?EnhancedVolcano



```




## Granular Cells

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DimPlot(SO8, group.by = "class.JGA")

DimPlot(SO8, group.by = "class.JGA", 
        cols = c("EG Mesangial Cell" = "yellow",
                 "IG Mesangial Cell" = "yellow", 
                 "Efferent VSMC" = "yellow", 
                 "Afferent VSMC" = "yellow", 
                 "Pericyte" = "yellow", 
                 "Granular Cell" = "blue")) +
  ggtitle("")




```


```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

df9 <- FindMarkers(SO8, ident.1 = c("Granular Cell"), min.pct = 0.1, logfc.threshold = 0.25)

df9 <- df9 %>% filter(p_val_adj < 0.05)

EnhancedVolcano(df9,
                lab = rownames(df9),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-4, 4),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

```


## Afferent vs. Efferent VSMC

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

df10 <- FindMarkers(SO8, ident.1 = c("Afferent VSMC"), ident.2 = c("Efferent VSMC"), min.pct = 0.1, logfc.threshold = 0.25)

EnhancedVolcano(df10,
                lab = rownames(df10),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-4, 4),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

```

## Pericytes vs. VSMC

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

df11 <- FindMarkers(SO8, ident.1 = c("Pericyte"), ident.2 = c("Afferent VSMC","Efferent VSMC"), min.pct = 0.1, logfc.threshold = 0.25)

EnhancedVolcano(df11,
                lab = rownames(df11),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-4, 4),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

```


# IG Mes Pathways

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}


mesDEGs <- FindMarkers(SO8, ident.1 = c("IG Mesangial Cell"), ident.2 = c("EG Mesangial Cell"), min.pct = 0.25, logfc.threshold = 0.25)

DEG_list <- mesDEGs

markers <- DEG_list %>% rownames_to_column(var="SYMBOL")

head(markers, n = 50)

ENTREZ_list <- bitr(geneID = rownames(DEG_list),   #input gene id
                    fromType = "SYMBOL",           #input id type
                    toType = "ENTREZID",           #output id type
                    OrgDb = "org.Mm.eg.db"         #annotation Db
                    )

markers <-  ENTREZ_list %>% inner_join(markers, by = "SYMBOL")

# Removing genes that are not statistically significant. 
markers <-  markers %>% dplyr::filter(p_val_adj < 0.05)
head(markers, n = 50)

pos.markers <-  markers %>% dplyr::filter(avg_log2FC > 0) %>%  arrange(desc(abs(avg_log2FC)))
head(pos.markers, n = 50)

pos.ranks <- pos.markers$ENTREZID[abs(pos.markers$avg_log2FC) > 0]
head(pos.ranks)

pos_go <- enrichGO(gene = pos.ranks,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go

dotplot(pos_go) +         
        ggtitle("IG Mesangial Cell Upregulated Pathways") +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme_classic() + 
        scale_x_reverse()  # Reverses the x-axis
        

# rotate this plot around the y axis

dotplot(pos_go) +
    ggtitle("DCT1 Upregulated Pathways") +
    theme(plot.title = element_text(hjust = 0.5)) + 
    theme_classic() + 
    scale_x_reverse()  # Reverses the x-axis

dotplot(pos_go) +
    ggtitle("DCT1 Upregulated Pathways") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),          # Center the title
        legend.position = "left",                        # Move legend to the left
        axis.text.y = element_text(hjust = 0)            # Move y-axis labels to the right
    ) +
    scale_y_discrete(position = "right") +               # Position y-axis labels on the right
    scale_x_reverse()  

dotplot(pos_go) +
    ggtitle("DCT1 Upregulated Pathways") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "left",
        axis.text.y = element_text(hjust = 0, size = 10)  # Adjust size if needed
    ) +
    scale_y_discrete(position = "right") +
    scale_x_reverse()

dotplot(pos_go) +         
        ggtitle("IG Mesangial Cell Upregulated Pathways") +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme_classic() + 
        scale_x_reverse()  # Reverses the x-axis


dotplot(pos_go) +         
    ggtitle("IG Mesangial Cell Upregulated Pathways") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        axis.text.y = element_text(lineheight = 1, margin = margin(r = 10))  # Ensures single line with spacing
    ) +
    scale_x_reverse()

dotplot(pos_go) +         
    ggtitle("IG Mesangial Cell Upregulated Pathways") +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5),
        axis.text.y = element_text(lineheight = 1),
        plot.margin = margin(t = 10, r = 50, b = 10, l = 150)  # Increase left margin
    ) +
    scale_x_reverse()

```

# EG Mes Pathways

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}


mesDEGs <- FindMarkers(SO8, ident.1 = c("EG Mesangial Cell"), ident.2 = c("IG Mesangial Cell"), min.pct = 0.25, logfc.threshold = 0.25)

DEG_list <- mesDEGs

markers <- DEG_list %>% rownames_to_column(var="SYMBOL")

head(markers, n = 50)

ENTREZ_list <- bitr(geneID = rownames(DEG_list),   #input gene id
                    fromType = "SYMBOL",           #input id type
                    toType = "ENTREZID",           #output id type
                    OrgDb = "org.Mm.eg.db"         #annotation Db
                    )

markers <-  ENTREZ_list %>% inner_join(markers, by = "SYMBOL")

# Removing genes that are not statistically significant. 
markers <-  markers %>% dplyr::filter(p_val_adj < 0.05)
head(markers, n = 50)

pos.markers <-  markers %>% dplyr::filter(avg_log2FC > 0) %>%  arrange(desc(abs(avg_log2FC)))
head(pos.markers, n = 50)

pos.ranks <- pos.markers$ENTREZID[abs(pos.markers$avg_log2FC) > 0]
head(pos.ranks)

pos_go <- enrichGO(gene = pos.ranks,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go

dotplot(pos_go)

dotplot(pos_go) +
        ggtitle("EG Mesangial Cell Upregulated Pathways") +
        theme(
        plot.title = element_text(hjust = 0.5),
        legend.position = "right",                       
        axis.text.y = element_text(hjust = 0)
    ) +
    scale_y_discrete(position = "right") + 
  theme_classic()

dotplot(pos_go) +
    ggtitle("EG Mesangial Cell Upregulated Pathways") +
    theme_classic() +  # Apply the classic theme first
    theme(
        plot.title = element_text(hjust = 0.5),    # Center the title
        legend.position = "left",                  # Move legend to the left
        axis.text.y = element_text(hjust = 0)      # Align y-axis text to the left (for right-side labels)
    ) +
    scale_y_discrete(position = "right")           # Move y-axis labels to the right

```


# Pericytes vs. VSMC

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.height=10}


mesDEGs <- FindMarkers(SO8, ident.1 = c("Pericyte"), ident.2 = c("Efferent VSMC", "Afferent VSMC"), min.pct = 0.25, logfc.threshold = 0.25)

DEG_list <- mesDEGs

markers <- DEG_list %>% rownames_to_column(var="SYMBOL")

head(markers, n = 50)

ENTREZ_list <- bitr(geneID = rownames(DEG_list),   #input gene id
                    fromType = "SYMBOL",           #input id type
                    toType = "ENTREZID",           #output id type
                    OrgDb = "org.Mm.eg.db"         #annotation Db
                    )

markers <-  ENTREZ_list %>% inner_join(markers, by = "SYMBOL")

# Removing genes that are not statistically significant. 
markers <-  markers %>% dplyr::filter(p_val_adj < 0.05)
head(markers, n = 50)

pos.markers <-  markers %>% dplyr::filter(avg_log2FC > 0) %>%  arrange(desc(abs(avg_log2FC)))
head(pos.markers, n = 50)

pos.ranks <- pos.markers$ENTREZID[abs(pos.markers$avg_log2FC) > 0]
head(pos.ranks)

pos_go <- enrichGO(gene = pos.ranks,           #a vector of entrez gene id
                   OrgDb = "org.Mm.eg.db",    
                   ont = "BP",
                   readable = TRUE)              #whether mapping gene ID to gene Name

pos_go

dotplot(pos_go) +
        facet_grid(scale="free") +          #ggplot2 functions
        ggtitle("DCT1 Upregulated Pathways") +
        theme(plot.title = element_text(hjust = 0.5)) + theme_classic()
```

# UMAPs for RNAscope


```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}




FeaturePlot(SO8, "Pdgfrb") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Pdgfra") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Gata3") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )


FeaturePlot(SO8, "Adora1") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Hpse2") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Tenm2") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Dgkg") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Rgs5") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )

FeaturePlot(SO8, "Agtr1a") + 
  ylab("UMAP 2") +
  xlab("UMAP 1") +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.line = element_line(size = 1, colour = "black"),
    axis.text = element_blank(),          # Remove axis text
    axis.ticks = element_blank(),         # Optional: Remove axis ticks
    text = element_text(size = 20)
  )


```


# Violin Plots for RNAscope

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

VlnPlot(SO8, features = "Pdgfrb", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Pdgfra", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Gata3", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Adora1", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Hpse2", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Tenm2", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Dgkg", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Rgs5", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 

VlnPlot(SO8, features = "Agtr1a", group.by = "class.JGA", pt.size = 1) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        text = element_text(size=20),
        axis.text.x = element_text(color = "black", size = 16, angle = 45, hjust = 1, vjust = 1),
        legend.position = "none"
        ) + xlab("") 
        
```        
        
        
# Slc12a1-Lineage

# Load Dataset

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

SO_TAL <- readRDS(here("Datasets", "TAL_TenX.rds"))

SO_TAL2 <- subset(x = SO_TAL, subset = class.TAL == "Prolif", invert = TRUE)

Idents(SO_TAL2) <- SO_TAL2@meta.data$orig.ident

head(SO_TAL2@meta.data)

SO_TAL3 <- subset(x = SO_TAL2, downsample = 2110)

DimPlot(SO_TAL3, group.by = "class.TAL")


```

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DefaultAssay(SO_TAL3) <- "RNA"

markers.to.plot3 <- c("Slc12a1",
                      "Cldn10",
                      "Cldn16",
                      "Nos1"
                            )

DotPlot(SO_TAL3,
        features = markers.to.plot3,
        dot.scale = 8,
        dot.min = 0,
        scale.max = 50,
        scale.min = 0,
        col.min = -2.5,
        col.max = 2.5,
        scale = F,
        group.by = "class.TAL") +
  coord_flip() +
  theme_classic() +
  ggtitle("Populations Markers") +
  theme(axis.line = element_line(size = 1, colour = "black"),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        text = element_text(size = 20),
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5)) +
  xlab(NULL) +
  ylab(NULL)


```  

## MD Cells

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}


DimPlot(SO_TAL3, group.by = "class.TAL", 
        cols = c("TAL B" = "yellow",
                 "TAL A" = "yellow",
                 "MD" = "blue")) +
  ggtitle("")


```



```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

Idents(SO_TAL3) <- SO_TAL3@meta.data$class.TAL

df13 <- FindMarkers(SO_TAL3, ident.1 = c("MD"), min.pct = 0.1, logfc.threshold = 0.25)

df13 <- df13 %>% filter(p_val_adj < 0.05)

EnhancedVolcano(df13,
                lab = rownames(df13),
                title = (""),
                subtitle = NULL,
                caption = NULL,
                x = 'avg_log2FC', 
                legendLabels = NULL, 
                FCcutoff = 0.25, 
                y = 'p_val_adj', 
                labSize = 4, 
                legendIconSize = 4, 
                drawConnectors = T, 
                xlim = c(-5.5, 5.5),
                widthConnectors = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_classic()

```



```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}


FeaturePlot(SO, "Pdgfra")

VlnPlot(SO, "Pdgfra", group.by = "class.Merge")

FeaturePlot(SO_TAL3, "Nt5c1a", order = TRUE)

FeaturePlot(SO8, "Ngf")

VlnPlot(SO8, "Acta2")
VlnPlot(SO8, "Agtr1a")

```

# Pathways Analysis

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

SO8@meta.data$Cell <- SO8@meta.data$class.JGA

SO_TAL3@meta.data$Cell <- SO_TAL3@meta.data$class.TAL

SO <- merge(x = SO8, y = SO_TAL3)

SO <- NormalizeData(object = SO)
SO <- FindVariableFeatures(object = SO)
SO <- ScaleData(object = SO)
SO <- RunPCA(object = SO)
SO <- FindNeighbors(object = SO, dims = 1:30)
SO <- FindClusters(object = SO)
SO <- RunUMAP(object = SO, dims = 1:30)
DimPlot(object = SO, reduction = "umap")

DimPlot(object = SO, reduction = "umap", group.by = "Cell")

VlnPlot(SO, "nCount_RNA", group.by = "Cell")



```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

seurat_object <- SO

Idents(SO) <-SO@meta.data$Cell

Idents(seurat_object) <- seurat_object@meta.data$Cell
data.input <- seurat_object[["RNA"]]@data # normalized data matrix
# For Seurat version >= “5.0.0”, get the normalized data via `seurat_object[["RNA"]]$data`
labels <- Idents(seurat_object)
meta <- data.frame(labels = labels, row.names = names(labels)) # create a dataframe of the cell labels

cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels")

cellChat <- createCellChat(object = SO, group.by = "ident", assay = "RNA")

CellChatDB <- CellChatDB.mouse # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)

CellChatDB.use <- CellChatDB
cellchat@DB <- CellChatDB.use

cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
future::plan("multisession", workers = 4) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
#> The number of highly variable ligand-receptor pairs used for signaling inference is 692

cellchat <- computeCommunProb(cellchat, type = "triMean")

cellchat <- filterCommunication(cellchat, min.cells = 10)

cellchat <- computeCommunProbPathway(cellchat)

cellchat <- aggregateNet(cellchat)


saveRDS(cellchat, file = here("CellChat_JGA.rds"))
cellchat <- readRDS(here("CellChat_JGA.rds"))

Idents(object = cellchat) <- cellchat@meta.data$Cell

df.net <- subsetCommunication(cellchat)

df.net

write.csv(df.net, here("CellChat_JGA.csv"))

groupSize <- as.numeric(table(cellchat@idents))
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")

```


```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

mat <- cellchat@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}
pathways.show <- c("COLLAGEN") 
# Hierarchy plot
# Here we define `vertex.receive` so that the left portion of the hierarchy plot shows signaling to fibroblast and the right portion shows signaling to immune cells 
vertex.receiver = seq(1,4) # a numeric vector. 
netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver)
# Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")

par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")

par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
#> Do heatmap based on a single object

netAnalysis_contribution(cellchat, signaling = pathways.show)

runCellChatApp(cellchat)
```


```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

DimPlot(object = SO8)

FeaturePlot(SO8, "Adora1")

FeaturePlot(SO8, "Limch1")


```

# Session Info

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

sessionInfo()

```


  