---
title: "SoupX and Doublet Removal for TAL control sample"
author: "Xiao-Tong Su"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: 
      collapsed: false
      smooth_scroll: false
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_new_packages, echo=T, error=FALSE, message=FALSE, warning=FALSE}

if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
if (!require("DoubletFinder")) {BiocManager::install('DoubletFinder'); require("DoubletFinder")} # To install DoubletFinder, run this remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
if (!require("here")) {install.packages("here"); require("here")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("SoupX")) {install.packages("SoupX"); require("SoupX")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
set.seed(1234)

```

# SoupX

```{r SoupX, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

sampleid <- "Control_1"  #Change
condition <- "Control" #Change

# Load data and estimate soup profile
tod = Seurat::Read10X_h5(here("raw_feature_bc_matrix.h5"))
toc = Seurat::Read10X_h5(here("filtered_feature_bc_matrix.h5"))
sc = SoupChannel(tod,toc)

#Make the Seurat ojbect from the filtered control data
SO <- Read10X_h5(here("filtered_feature_bc_matrix.h5"))
SO <- CreateSeuratObject(counts = SO, project = "TAL")  #Change

#Cluster the cells with Seurat
SO <- SCTransform(SO, verbose = F)
SO <- RunPCA(SO, verbose = F)
SO <- RunUMAP(SO, dims = 1:40, verbose = F)
SO <- FindNeighbors(SO, dims = 1:40, verbose = F)
SO <- FindClusters(SO, verbose = T)

meta_SO <- SO@meta.data
umap_SO <- SO@reductions$umap@cell.embeddings

clusters <- setNames(meta_SO$seurat_clusters, rownames(meta_SO))

#Sanity check, they should be equal
length(clusters)
nrow(sc$metaData)

sc <- setClusters(sc, clusters)
sc <- setDR(sc, umap_SO)

#Estimate rho
sc = autoEstCont(sc)
#Clean the data
SO_out = adjustCounts(sc)

#Create a new Seurat Object out of the cleaned data
SO <- CreateSeuratObject(SO_out)

```

# Run UMAP

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

# Add metadata
SO$orig.ident <- "Diet K Distal"
SO <- AddMetaData(object = SO, metadata = sampleid, col.name = "Rep") 
SO <- AddMetaData(object = SO, metadata = condition, col.name = "Diet") #Change
SO[["percent.mt"]] <- PercentageFeatureSet(SO, pattern = "^mt-")
SO
head(SO@meta.data)

# QC and Filtering (low quality cells)
f4 <- VlnPlot(SO, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
f4

# Filter out high or low UMI cells
SO.f <- subset(SO, subset = nCount_RNA > 500
               & nCount_RNA < 20000
               & percent.mt < 10)
f5 <- VlnPlot(SO.f, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
f5
SO.f

# Pre-process standard workflow
SO.f <- NormalizeData(object = SO.f)
SO.f <- FindVariableFeatures(object = SO.f)
SO.f <- ScaleData(object = SO.f)
SO.f <- RunPCA(object = SO.f)
ElbowPlot(SO.f, 50)

# PCs between 30-40
SO.f <- FindNeighbors(object = SO.f, dims = 1:40)
SO.f <- FindClusters(object = SO.f, resolution = 0.2)
SO.f <- RunUMAP(object = SO.f, dims = 1:40)

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

DimPlot(SO.f, 
        reduction = "umap",
        label = TRUE)

p9 <- VlnPlot(SO.f, 
        features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
        stack = TRUE, 
        flip = TRUE,
        pt.size = 0,
        fill.by = "ident") +
  theme(legend.position = "none", 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 0, hjust = .5),
        axis.title.x = element_blank()) +
  ggtitle("Pre-DoubletFinder")
p9

FeaturePlot(SO.f,
            features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))

markers.to.plot1 <- c("Egf",          # TAL, DCT1
                      "Umod",         # TAL, DCT1
                      "Slc12a1",      # TAL
                      "Cldn10",
                      "Cldn16",
                      "Slc12a3",      # DCT
                      "Slc8a1",       # DCT2, CNT
                      "Slc5a12",      # PT-S1
                      "Aqp2",         # PC
                      "Slc26a4",      # IC-B
                      "Lrp2",         # PT
                      "Flt1",         # Endo
                      "Pdgfrb",       # Peri
                      "Slc4a1",       # IC-A
                      "Top2a",        # Proliferation
                      "Nphs1",        # Podo
                      "Pvalb",        # DCT1
                      "Ptprc")        # Immune

VlnPlot(SO.f, 
        features = markers.to.plot1,
        stack = TRUE, 
        flip = TRUE,
        pt.size = 0,
        fill.by = "ident") +
  theme(legend.position = "none", 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 0, hjust = .5),
        axis.title.x = element_blank()) + 
  stat_summary(fun = median,
        geom = "crossbar",
        width = 0.3,
        size = 0.1,
        position = position_dodge(width = 0.5))

DotPlot(SO.f,
        features = markers.to.plot1,
        dot.scale = 8,
        dot.min = 0,
        scale.max = 100,
        scale.min = 0,
        col.min = -2.5,
        col.max = 2.5) +
  coord_flip()

t1 <- table(Idents(SO.f))
t1

prop.t1 <- prop.table(t1) 
prop.t1

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center', fig.height = 8, fig.width = 10}

f <- FeaturePlot(SO.f,
             features = markers.to.plot1,
             cols = c("lightgrey", "royal blue"),
             combine = F)

for(i in 1:length(f)) {
  f[[i]] <- f[[i]] + NoLegend() + NoAxes()
}

f1 <- cowplot::plot_grid(plotlist = f)
f1
```

# DoubletFinder
## Find parameters for DoubletFinder

```{r find_parameters_1, echo=TRUE, error=FALSE, fig.align='center', message=FALSE, warning=FALSE, results=F}

# Calculate each combination of pN and pK
sweep.res.list_SO.f <- paramSweep_v3(SO.f, PCs = 1:50, sct = FALSE) 

```

```{r find_parameters_2, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

#Summarize each combination of pN and pK
sweep.stats_SO.f <- summarizeSweep(sweep.res.list_SO.f, GT = FALSE) 

#Select the pK that corresponds to max bcmvn to optimize doublet detection
bcmvn_SO.f <- find.pK(sweep.stats_SO.f)
pK <- bcmvn_SO.f %>% 
  filter(BCmetric == max(BCmetric)) %>%
  dplyr::select(pK) 

#See pK in the Values Environment
pK <- as.numeric(as.character(pK[[1]]))

```

```{r homotypic_doublets, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

# Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
annotations <- SO.f@meta.data$seurat_clusters  

homotypic.prop <- modelHomotypic(annotations)           
homotypic.prop

# 10X Multiplet Rate Table (the doublet ratio is # of cells revovered divided by 125000) https://kb.10xgenomics.com/hc/en-us/articles/360001378811-What-is-the-maximum-number-of-cells-that-can-be-profiled-

nExp_poi <- round(nrow(SO.f@meta.data) # To calculate cell number
                  /125000              # To calculate the doublet ratio
                  *nrow(SO.f@meta.data))
nExp_poi
nExp_poi_adj <- round(nExp_poi*(1-homotypic.prop))

```

## Identify doublets based on calculation

```{r doublet_finder, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

SO.f <- doubletFinder_v3(SO.f,
                        PCs = 1:20,
                        pN = 0.25,
                        pK = pK,
                        nExp = nExp_poi_adj,
                        reuse.pANN = FALSE, sct = FALSE)
colnames(SO.f@meta.data)[9] <- "pANN"
colnames(SO.f@meta.data)[10] <- "DF.class"
head(SO.f@meta.data)
table(SO.f@meta.data$DF.class)

```

## Subset singlets and remove mitochondrial genes

```{r subset, echo=TRUE, error=FALSE, fig.align = 'center', message=FALSE, warning=FALSE}

SO.f_singlets <- subset(SO.f, DF.class == "Singlet")
SO.f_singlets <- SO.f_singlets[!grepl("^mt-", rownames(SO.f_singlets)), ]
SO.f_singlets

#Sanity Check
counts <- GetAssayData(SO.f_singlets, assay = "RNA")
mito.genes <- grep(pattern = "^mt-", x = rownames(x = counts), value = TRUE) 
mito.genes #should be zero

rm(counts)
DimPlot(SO.f_singlets, reduction = "umap")

rdsName<- paste0(sampleid, ".rds")

saveRDS(SO.f_singlets, here(rdsName))

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center', fig.height = 8, fig.width = 10}

f2 <- FeaturePlot(SO.f_singlets,
             features = markers.to.plot1,
             cols = c("lightgrey", "royal blue"),
             combine = F)

for(i in 1:length(f2)) {
  f2[[i]] <- f2[[i]] + NoLegend() + NoAxes()
}

f3 <- cowplot::plot_grid(plotlist = f2)
f3
```

## More Plots

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

p1 <- FeaturePlot(SO.f,
            features = c("nFeature_RNA", "nCount_RNA", "percent.mt")) & 
  theme(plot.subtitle = element_text(hjust = 0.5)) & 
  labs(subtitle = "Pre-DoubletFinder")
p2 <- FeaturePlot(SO.f_singlets,
            features = c("nFeature_RNA", "nCount_RNA", "percent.mt")) & 
  theme(plot.subtitle = element_text(hjust = 0.5)) & 
  labs(subtitle = "Post-DoubletFinder")
p3 <- DimPlot(SO.f, reduction = "umap", pt.size = 1, label = TRUE) + ggtitle("Clustering Pre-DoubletFinder")
p4 <- ggplot(bcmvn_SO.f, aes(pK, BCmetric, group = 1)) + 
             geom_point() +
             geom_line() +
      ggtitle("Highest Point is pK value used") +
      theme(plot.title = element_text(size = 15, face = "bold"))
p5 <- DimPlot(SO.f, group.by = "DF.class", pt.size = 1) + ggtitle("Doublet and Singlet Distribution")
p6 <- FeaturePlot(SO.f, features = "pANN", pt.size = 1)

p7 <- VlnPlot(SO.f, 
        features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), 
        split.by = "DF.class",
        stack = TRUE,
        flip = TRUE)

p8 <- DimPlot(SO.f_singlets, reduction = "umap", pt.size = 1) +
      ggtitle("Clustering Post-DoubletFinder",
              subtitle = paste0(paste0(nrow(SO@meta.data)), " ", "nuclei", " ",
                                "pre-filtering", "\n",
                                paste0(nrow(SO.f@meta.data)," ", "nuclei", " ",
                                "post-filtering", "\n",
                                paste0(nrow(SO.f_singlets@meta.data)," ", "nuclei", " ",
                                "post-DoubletFinder"))))
p10 <- VlnPlot(SO.f_singlets, 
        features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
        stack = TRUE, 
        flip = TRUE,
        pt.size = 0,
        fill.by = "ident") +
  theme(legend.position = "none", 
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 0, hjust = .5),
        axis.title.x = element_blank()) +
  ggtitle("Post-DoubletFinder")


p1
p2
p3
p4
p5
p6
p7
p8
p9
p10

```

## Output Files

```{r txt, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center', eval=F}

txtName <- paste0(sampleid, " Nuclei Report.txt")

sink(here(txtName))

cat("Pre-Filtering", sep="\n")
cat(c(nrow(SO@meta.data), "nuclei"))
cat("\n")
cat("\n")
cat("Post-Filtering with Features/RNA/Mito Cut-Offs", sep="\n")
cat(c(nrow(SO.f@meta.data), "nuclei"))
cat("\n")
cat("\n")
cat("Post-Doublet Finder", sep="\n")
cat(c(nrow(SO_singlets@meta.data), "nuclei"))

sink()
```

```{r pdf, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center', eval = FALSE}

pdfName <- paste0(sampleid, ".pdf")

{
pdf(here(pdfName), width = 16, height = 9, onefile = TRUE)
plot(p1)
plot(p2)
plot(p3)
plot(p4)
plot(p5)

dev.off()
}
```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
sessionInfo()
```
